apiVersion: apps/v1
kind: Deployment
metadata:
  name: scan
  labels:
    app: scan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scan
  template:
    metadata:
      labels:
        app: scan
    spec:
      containers:
        - name: scan
          image: "username/scan:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
